### ISSUE TITLE
Full width header/footer

### ISSUE THREAD

**Issue by jeffturcotte** [imarc/boilerplate-archived#16]
Shouldn't the header be full width? I think this is a pattern we use much more often than what is currently implemented.

You can see the rough proof of concept on my fork: 
http://jeffturcotte.github.com/boilerplate/markup.html

Here is the commit:
https://github.com/jeffturcotte/boilerplate/commit/7ac09aba12f16ead3580687e3d8d6331b471699e

If we agree, we can work to figure out the best implementation.

**Comment by khamer** [comment]
I see Jeff's point, though I'll let @marcelmoreau or such pick what he thinks is is more useful to him.

The 'right way' to implement what Jeff proposed would be to flip the hierarchy of `.site` with the major containers:

``` html
<body>
    <div class="site">
        <header class="primary">...</header>
        <div class="torso">...</div>
        <footer class="primary">...</footer>
    </div>
</body>
```

to

``` html
<body>
    <header class="primary">
        <div class="site">...</div>
    </header>
    <div class="torso">
        <div class="site">...</div>
    </div>
    <footer class="primary">
        <div class="site">...</div>
    </footer>
</body>
```

Jeff's already commented that perhaps 'site' is a poor name for the second example, which is fine. Perhaps we should do both a div around all three and divs within them, I just want it to be consistent, and it's be nice if the class names didn't including things like "outer_", "inner_", "wrapper", etc.

**Comment by jeffturcotte** [comment]
.matte

**Comment by mattsah** [comment]
I'm still not 100% clear on this site thing and why we feel the need to create wrapping elements of any sorts.  The number of child elements you will find in one of these three main areas of the page is pretty low, ensuring the inner elements children are all of a certain width does not seem very difficult.  Plus, I'd rather have a more specific selector on something like that, e.g:

``` css
body > header > *,
body > div > *,
body > footer > * {
    width: 960px;
    margin: 0 auto;
}
```

Rather than just `.site` or even `header > .site`.  

Also, with torso I'm not sure why we're not just using the "main" div directly.

``` html
<body>
    <header class="primary">
    </header>
    <div class="main" role="main">
    </div>
    <footer class="primary">
    </footer>
</body>
```

**Comment by jeffturcotte** [comment]
@mattsah I agree the less wrapping elements the better, but I don't think we want to style all direct descendants with a width of X. The best example I can think of right now would be a utility nav in the header. (header > nav.utility) _EDIT: I'm not totally opposed to the dd selector, but it just means we would need a rule that there is always some kind of container element within header/.torso/footer/etc._

As for .main vs .torso, .torso is used to encapsulate both .main and any supplemental columns (asides) you might have.

**Comment by khamer** [comment]
`.torso` also contains `aside.primary` and such, whereas `.main` is really just the main content.

I talked to Christian, and I'm at least convinced that Jeff's right, we should plan on full width `header`/`.torso`/`footer`.  We dropped direct child selectors as much as possible from Boilerplate itself, because they can be fragile, and there may still be reasons to wrap it all in a `.site`, so I'd still rather use `header.primary`, `header.secondary`, `.torso`, `footer.primary`, etc., to target those containers instead of `body > header` and such.

Also, I feel like `.torso > *` would cause more problems than `.torso .matte`. The fixed width is likely to be in a media query, So having a wildcard rule that applies to a lot of elements toggling on/off with a media query seems more likely to yield unexpected behavior than just changing one container.

**Comment by mattsah** [comment]
@jeffturcotte 

I also agree we don't want to style them that way.  I was moreso using it as an example just to explain it can be done on the child elements.

@khamer 

See above.  I agree that to some extent `.torso` breaks this, but in that event, I'd still say we should only be looking at torso.  Header's generally have `nav` which is perfectly fine to set the width and auto margin on.  Footers are often broken into columns in which case a `<div class="group">` with some other class might be more suitable, e.g.:   `<div class="sitemap group">`

The overall point here is that whatever the inner elements are can have semantic or more semantic names of their own, and may or may not be needed depending on the site.  On the home page this is probably particularly true of torso as well in most cases.

Jeff's fork already seems to do as I'm suggesting on the header with the `nav` elements being different colors and the width being set on their `ul` children.  The torso and footer, however, make some assumptions that the background color is always consistent with the main background color.  This usually differs on footer I'd suspect.

Still waiting for this to be published but it should have an example based on Jeff's when it's done:

http://mattsah.github.com/boilerplate/markup

If not, you can just clone it and look at `markup.html` on your system.  Imma go do vacationy stuff now.

**Comment by marcelmoreau** [comment]
Sounds like we all agree that removing the wrapping `.site` div is a good idea so we can achieve our full width style. Since that was the question for this issue, I will close this issue. If you would like to carry on conversation about  other boilerplate items, please open another issue.
