### ISSUE TITLE
HTML Difference?

### ISSUE THREAD

**Issue by jeffturcotte** [imarc/boilerplate-archived#2]
From Dave: 

What's the difference between the markup_test.html and html5_test.html? Do we want to be maintaining css that works with two sets of markup? If there is a difference, should we set the meta description to describe what each file is for instead of just "iMarc, LLC"

**Comment by khamer** [comment]
So @davetufts, I'm okay with us only having one. html5_test I used HTML5 tags  heavily, whereas markup_test I mostly just updated/tweaked what we already had. I think @marcelmoreau is in favor of making the transition to using HTML5 tags whenever appropriate, so we might be able to drop markup_test in favor of html5_test.

**Comment by davetufts** [comment]
Based on all the conversations I've heard, I think we should go with HTML5 as the boilerplate default. If some project requires additional backward compatibility, we can deal with it individually. But it would be ideal to have default css for one default markup. Should I enter a separate issue to - remove the one of the HTML files and clean up the CSS to work with the other.

**Comment by mattsah** [comment]
I'm still not a fan of my HTML requiring Javascript to work properly.... :(

I frankly thing we should stick with XHTML until XHTML5 is supported by the vast majority of browsers.  I understand XHTML is actually XML served as HTML currently -- but I suspect given the development of HTML5/XHTML that the acceptance of the XHTML mime-type will become common at the same time as those tags actually being supported.

I'm a huge fan of using div with the first class bieng the X/HTML5 tag in which case CSS _should_ assuming people actually stick to it, be able to be changed in a heartbeat of replace methods.   div.header => header

**Comment by jeffturcotte** [comment]
On one hand, I agree. IE8 is still a big player, and right now we are doing bigger sites that tend to have large enterprise audiences. Sometimes they have requirements that won't necessarily fit well with a solution that requires javascript. This _should not_ stop us from using HTML5 for the markup test here, or even HTML5 markup on the majority of our sites, but I think we can meet in the middle and support both HTML5 and XHTML in the base css with barely any effort at all.

Example:

```
header,
div.header {
    background: black;
}
```

**Comment by mattsah** [comment]
Yes, this is something I've done.  The only argument I can see from this is the size of the CSS which I would hope would be relatively negligible.  The key point here is _why_ are we using the elements.  Header, functionally (at the moment) I don't think does much more than be nice.  It's not like <video> where certain extra functionality is actually picked up.

Also, when clients say they want an HTML5 site (if any of them do say that), we all know damn well they're not talking about semantics elements which they couldn't care less about.  These may have more reason to be used in another 2 - 3 years when they are actually being used to identify content in different ways (perhaps google is already doing so for search ranking, but I doubt it has much effect).

Just saying.

I guess the only one I'm not totally in favor with would be HTML5 only.  For me it's either both or XHTML.

BTW, I hope when browsers actually do get there iMarc will be serving it's HTML as application/xhtml+xml -- but that's _probably_ just me.

**Comment by khamer** [comment]
Both is the worst. Not only does it complicate JavaScript, if we're letting people mix its multiplicative-

``` css
body > header nav { }
```

becomes

``` css
body > header nav, body > header .nav, body > .header nav, body > .header .nav { }
```

and all that nonsense.

But, this is a tangent. iMarc has already started using HTML5 tags for normal markup (iMarc.net, Rapid7) with the shiv. `markup_test` is mostly consistent with how iMarc is currrently using HTML5, whereas `html5_test` I used HTML5 tags as correctly as I could, as right now, we're not coding either properly. For example, here's a snippet from iMarc.net:

``` html
<body>
    <div class="header_out">
        <header class="group">
            ...
            <nav class="nav_header">
                ...
                <ul>
                    <li>
                        <a href="/work">Our Work</a>
                    </li>
                    ...
                </ul>
            </nav>
        </header>
    </div>
</body>
```
- Our top level tags in the `body` tag aren't header tags (HTML5) and don't have a header class (our previous XHTML rules.)
- We're using both a `ul` (XHTML) and a `nav` tag (HTML5). For XHTML, we don't need a nav tag (the class should be on the ul) and for HTML5 we should have plain `a` tags inside of the `nav`.
- The `header` `nav` has a "nav_header" class.
- Things like `header` having a class of "group" screams to me that we need to fix our default CSS for `header` tags.
  I **do not** want to get into the semantics, I just want to focus on that this isn't good markup.

I want to have a better boilerplate for projects that's in a format we're all comfortable with so we can all work on improving it and are willing to change it for match client sites. Right now, we're working off of the HTML5 Boilerplate, and I don't think that's a good foundation for our markup or CSS style, as it encourages a lot of bulk that we're treating as a black box. Plus, I think a better boilerplate will help us all unify around consistent markup again.

So, all that said, I agree with @davetufts. @mattsah and @jeffturcotte - you should look at the [source of the shiv](https://github.com/aFarkas/html5shiv/blob/master/src/html5shiv.js) (only 300 lines) if you haven't. It mostly just adds static content to the DOM, and is slightly over 2kb minified. It doesn't walk through the document or interact with the page's markup at all. Is this really a risk point we should be worried about?

**Comment by mattsah** [comment]
I think @jeffturcotte was aware of the doubling and was comfortable with it.  The point is not that would double everything per se, but that the base stuff could be doubled.  Obviously with each site we would make a determination as to which markup it was using and then work with that from there on, but the common/shared/base CSS would contain both for the flexibility of starting either.

On the issue of `nav`, two things.  The `nav` for a site would/should essentially be the same regardless.  Despite including a `nav` tag, I would argue that `ul` is still the most appropriate item for presenting the _menu_ of a site.  To my knowledge, in HTML5, `nav`, was never designed to _replace_ the `ul` but simply to wrap it.  This means really our HTML/XHTML should be almost exactly the same:

``` html
<div class="nav">
    <ul>
        <li></li>
        ....
    </ul>
</div>
```

``` html
<nav>
    <ul>
        <li></li>
        ....
    </ul>
</nav>
```

I'm not sure what happened to it, but I used to have a gist from when I was freelancing called "Bulletproof Nav", this was a reminder for me that navigation related uls should always be inside a div.  All HTML5 has done is turn that `div` into a `nav` so presumably both humans and bots can parse the meaning of those `ul`s more easily.

I'm aware of how the shiv works and that it very limited in terms of the JS it does to enable the extra elements.  I'm not exactly sure where @jeffturcotte stands completely on this and I don't want to put words in his mouth.

For me at least for me, using the shiv is _not due to any real or perceived risk_.

My point is simply one of practicality and benefit, using semantic HTML5 is essentially still pointless at this stage of the game.  There are new elements of HTML5 which actually add ability and behavior to the browser... these seem to be what _clients actually want_ when they say they want HTML5.  Hell, this is probably what _iMarc actually wants_ when it says it wants HTML5.

That said, there is _some_ value in "cutting your teeth" with HTML5 before it does matter, but that value is overrated.  The fact of the matter is that using HTML5 now or later is going to result in some people using it improperly.

The difference of not using it now, however, is that of giving it time to mature as a better defined and interpreted standard.  This will come partly from the community and no doubt partly from WHATWG which has already made it clear (I believe) that they want HTML to be a "living standard."

Lastly, HTML5 just sucks: http://scriptogr.am/mattsah/post/html5-sucks-part-1

**Comment by mattsah** [comment]
BTW, just to be clear, the link to my HTML5 sucks article was not completely tongue in cheek.  There is some useful critique I think available in that post, like the example of an invalid document:

``` html
<!doCTYPE htMl>

<meta charset=utf-8>
<title>blah</title>

<p>I'm the content
<a href="#">
   <ul class=wtf id='garbage'>
      <li>hows this work for you?
      <p>Am I my own invalidly placed element?
      <li>Am I?  Aparently not</li>
   </ul>
</a>
```

vs. a valid HTML5 document

``` html
<!doCTYPE htMl>

<meta charset=utf-8>
<title>blah</title>

<p>I'm the content</p>
<a href="#">
   <ul class=wtf id='garbage'>
      <li>hows this work for you?
      <p>Am I my own invalidly placed element?
      <li>Am I?  Aparently not</li>
   </ul>
</a>
```

**Comment by davetufts** [comment]
Ignoring what application type we serve, or if we need JS to make certain HTML compatible with older browsers, or even which HTML file we use – the original question was (simplified):

**Do we want a boilerplate that has two markup files – one that uses HTML5 tags and one that doesn't?**

My answer would be: _no, we should have a single starting point and each project can grown and diverge from there._

If we at least all agree on that, maybe picking the start point (HTML5 or pseudo-HTML5) seems like a better conversation for real-life. Nobody's going to change their mind in these comments.

**Comment by jeffturcotte** [comment]
![2litPb4](https://f.cloud.github.com/assets/65089/80276/fbf6d64a-623c-11e2-844d-162f1df2de61.gif)

and yes, one markup file.

**Comment by marcelmoreau** [comment]
I don't know much about mime type or application settings but my input:
- One file – no duplication for HTML5 and XHTML. That's a nightmare.
- Let it be HTML5 – part of this whole boilerplate process will be our research on using things correctly/semantically. I don't know why iMarc should not use an existing standard when companies large and small seem to be progressing just fine.
- Only older browser verions will rely on JS to execute their HTML properly.
- If your new project can't rely on the shiv, **then don't use it** use it and the new iMarc boilerplate.

**Comment by khamer** [comment]
I also agree, one markup file, and I agree, if we want to revisit whether iMarc writes HTML5 or not, I agree @davetufts, that sounds like a better conversation to have separately. Closing issue.
