### ISSUE TITLE
mobile nav overlay scroll issue

### ISSUE THREAD

**Issue by marcelmoreau** [imarc/boilerplate-archived#71]
I made a [new branch](
https://github.com/imarc/boilerplate/tree/component-mobile-nav-two) for more work on this. The attached video shows an issue with the body scrolling behind the menu. The overlay does not fill. I was able to resolve this by toggling overflow and position on the body. Can you look at the video of the issue and refactor what I did provided you like the fix?
[mobile-menu.mov.zip](https://github.com/imarc/boilerplate/files/725176/mobile-menu.mov.zip)

**Comment by mbfitz** [comment]
I was just trying to use this on a personal site and noticed a couple of things:

If you change the option to come in from the right - the CSS doesn't match up. It should be 0% instead of 100%in this rule: 
 `&.open.right {
        transform: translateX(0%);
   }`

Also - when opening from the right, can we add an "x"  to the open menu (might need this on both, actually)? When in left mode - you can still see the menu toggle so it's effective, but when it slides in from the right it hides it and there's no clear way to close the menu (you can click anywhere, but it's not obvious).

**Comment by TommyChanthaboune** [comment]
@marcelmoreau 

I appreciate your effort to fix this issue. There was one side effect with it however. If you were to scroll down a bit and hit the menu button it would shoot the window position to the top.

Also I saw a class that was added and nested within `body` in `styles.scss` to make this work. Instead, I would like to keep all behavior and styles in regards to the mobile nav encapsulated within the components sass mixin or the jQuery plugin. 

I landed on a solution that uses inline styles on the `html` and `body` tag to prevent scrolling. There is method in the jQuery plugin to toggle it depending if the menu is open or not.

@mbfitz 

I fixed the specificity issue it should work now. In regards to your last problem, I'm not going to fix that because it sounds more like a site specific issue. Instead, I exposed a method `closeAll()` that you're able to bind to in order to close the menus. For example

```javascript

// initialize secondary mobile nav
var filters = $('.filters').mobileNavigation({
    directionFrom: 'right'
});

$('.close').on('click', function(){
    filters.closeAll()
})

```

Hopefully this makes it flexible enough that you can design and create a close button wherever you need to. I updated the documentation with this example.

**Comment by marcelmoreau** [comment]
I made some cosmetic edits to this branch in order to get the mobile nav's search form to look correct in iPhone – search input had native OS styling and was cutting off.

You mentioned you wanted to keep things encapsulated within components/plugin, but `button.menu-toggle` must be targeted via the stylesheet. I needed to modify its hover/focus styles.

Can we move the mixin calls to the Components section of the SASS file with everything else?

I have concerns about using such a generic `.wrapper` class for site's wrapper. Can we name this something else? Adding this to older sites where we use this class liberally will create conflicts.
